kotlin.code.style=official
deploy.version=0.7.97-KBA-003
deploy.release=true
#发布命令 ./gradlew :skiko:publish -Pdeploy.release=true
dependencies.skia.windows-x64=m116-47d3027-1
dependencies.skia.linux-x64=m116-47d3027-1
dependencies.skia.macos-x64=m116-47d3027-1
dependencies.skia.windows-arm64=m116-47d3027-1
dependencies.skia.linux-arm64=m116-47d3027-1
dependencies.skia.macos-arm64=m116-47d3027-1
dependencies.skia.wasm-wasm=m116-47d3027-1
dependencies.skia.ios-x64=m116-47d3027-1
dependencies.skia.ios-arm64=m116-47d3027-1
dependencies.skia.iosSim-arm64=m116-47d3027-1
dependencies.skia.iosSim-x64=m116-47d3027-1
dependencies.skia.android-x64=m116-47d3027-1
dependencies.skia.android-arm64=m116-47d3027-1
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m
kotlin.version=2.0.21-KBA-001
skiko.awt.enabled=false
skiko.js.enabled=false
skiko.wasm.enabled=false
skiko.android.enabled=false
skiko.native.linux.enabled=false
skiko.native.mac.enabled=false
skiko.native.ios.enabled=true
skiko.native.ios.arm64.enabled=true
skiko.native.ios.simulatorArm64.enabled=true
skiko.native.ios.x64.enabled=true
'kotlin.mpp.applyDefaultHierarchyTemplate=false'
# This line needs for maven publication with ObjC defFile. Should be removed after Kotlin 1.8.20
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.applyDefaultHierarchyTemplate=false
skiko.native.enabled=true
